---

- hosts: all
  gather_facts: false
  tasks:
    - name: Copy and unarchive file
      unarchive:
        src: /opt/polemarch/packages/installer.tar
        dest: /tmp/bitdefender
        remote_src: no
