---

- hosts: all
  gather_facts: true
  vars:
    newline_character: "\n"
    services_running: []
    services_NOT_running: []
  tasks:      
  
    - name: Check if BitDefender is installed
      command: dpkg-query -W -f='${Status}' bitdefender-security-tools | grep 'install ok installed'
      register: is_installed
      failed_when: no
      changed_when: no
      when: ansible_facts['os_family'] == "Debian"

      
    - name: Creates directory
      file:
        path: /tmp/bitdefender
        state: directory
      when: is_installed.rc != 0
               
    - name: Copy and unarchive Bitdefender file
      unarchive:
        src: /packages/installer.tar
        dest: /tmp/bitdefender/
        remote_src: no
      when: is_installed.rc != 0
        
    - name: set installer file permissions
      file:
        dest: /tmp/bitdefender/installer
        mode: a+x
      when: is_installed.rc != 0
        
    - name: execute installer file
      ansible.builtin.command: ./installer
      args:
        chdir: /tmp/bitdefender/
      when: is_installed.rc != 0
      
    - name: Populate service facts
      ansible.builtin.service_facts:
      
    - name: check if TFA is installed
      fail:
        msg:  Bitdefender Security Tools Daemon service status
      when: ansible_facts.services["bdsec-daemon.service"] is not defined
      

