---

- hosts: all
  gather_facts: false
  tasks:      
               
    - name: Copy and unarchive file
      unarchive:
        src: /packages/installer.tar
        dest: /tmp/bitdefender/
        remote_src: no
        
    - name: set permissions
      file:
        dest: /tmp/bitdefender/installer
        mode: a+x
        
    - name: execute file
      command: ./tmp/bitdefender/installer
