---

- hosts: all
  gather_facts: false
  tasks:
    - name: If follow=yes, /path/to/file will be overwritten by contents of foo.conf
      unarchive:
        src: /opt/polemarch/playbooks/bitdefender/installer.tar
        dest: /tmp/bitdefender
        remote_src: no
