---

- hosts: all
  gather_facts: false
  tasks:      
  
    - name: Check if BitDefender is installed
      command: dpkg-query -W -f='${Status}' bitdefender-security-tools | grep 'install ok installed'
      register: is_installed
      failed_when: no
      changed_when: no
               
    - name: Copy and unarchive Bitdefender file
      unarchive:
        src: /packages/installer.tar
        dest: /tmp/bitdefender/
        remote_src: no
      when: is_installed.rc == 0
        
    - name: set installer file permissions
      file:
        dest: /tmp/bitdefender/installer
        mode: a+x
        
    - name: execute installer file
      command: ./tmp/bitdefender/installer
      when: is_installed.rc == 0
      
      
    - name: display BitDefender log
      debug: var=item
      with_file:
        - "/opt/bitdefender-security-tools/var/log/installer.log"
      when: is_installed.rc == 0
