---

- hosts: all
  gather_facts: false
  tasks:      
  
    - name: Check if foo is installed
      command: dpkg-query -l bitdefender-security-tools
        register: deb_check
        changed_when: False
               
    - name: Copy and unarchive file
      unarchive:
        src: /packages/installer.tar
        dest: /tmp/bitdefender/
        remote_src: no
        
    - name: set permissions
      file:
        dest: /tmp/bitdefender/installer
        mode: a+x
        
    - name: execute file
      command: ./tmp/bitdefender/installer
      when: deb_check.stdout.find('no packages found') != -1
