---

- hosts: all
  gather_facts: false
  tasks:
    - name: Copy and unarchive file
      unarchive:
        src: /opt/polemarch/packages/installer.tar
        dest: /tmp/bitdefender/
        remote_src: no
        
    - name: Copy file 
      ansible.builtin.copy:
        src: /opt/polemarch/packages/installer.tar
        dest: /tmp/installer.tar
        
    - name: Copy file 
      ansible.builtin.copy:
        src: /tmp/installer.tar
        dest: /tmp/bitas.tar
