
---

- hosts: all
  gather_facts: true
  tasks:       

    - name: Run Script
      shell: 'dpkg -l | grep policykit'
      register: results
      failed_when: no
      changed_when: no
      when: ansible_facts['os_family'] == "Debian"
      
    - debug: 
        msg: msg="{{ results.stdout_lines }}"
